import { useEffect, useRef, useState } from 'react';
import { supabase } from '../../../supabaseClient';

interface ImpactStats {
  co2Saved: number;
  itemsRescued: number;
  treesEquivalent: number;
  profitGenerated: number;
}

function useCountUp(target: number, duration: number = 2000, start: boolean = false) {
  const [value, setValue] = useState(0);

  useEffect(() => {
    if (!start || target === 0) return;
    let startTime: number | null = null;
    const step = (timestamp: number) => {
      if (!startTime) startTime = timestamp;
      const progress = Math.min((timestamp - startTime) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      setValue(Math.floor(eased * target));
      if (progress < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }, [target, duration, start]);

  return value;
}

function StatCard({
  icon,
  value,
  label,
  suffix,
  prefix,
  animate,
  color,
}: {
  icon: string;
  value: number;
  label: string;
  suffix?: string;
  prefix?: string;
  animate: boolean;
  color: string;
}) {
  const count = useCountUp(value, 2200, animate);

  const formatted = count >= 1000
    ? count.toLocaleString('en-GB')
    : count.toString();

  return (
    <div className="flex flex-col items-center text-center px-6">
      <div className={`w-12 h-12 flex items-center justify-center rounded-full mb-3 ${color}`}>
        <i className={`${icon} text-xl`}></i>
      </div>
      <div className="text-3xl font-bold text-white tracking-tight">
        {prefix}{formatted}{suffix}
      </div>
      <div className="text-sm text-gray-300 mt-1 whitespace-nowrap">{label}</div>
    </div>
  );
}

export default function ImpactStrip() {
  const [stats, setStats] = useState<ImpactStats>({
    co2Saved: 0,
    itemsRescued: 0,
    treesEquivalent: 0,
    profitGenerated: 0,
  });
  const [animate, setAnimate] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const fetchStats = async () => {
      const { data, error } = await supabase
        .from('scans')
        .select('decision, profit_gbp');

      if (error || !data) return;

      const buyScans = data.filter((s) => s.decision === 'BUY');
      const itemsRescued = buyScans.length;
      const co2Saved = itemsRescued * 22;
      const treesEquivalent = Math.floor(co2Saved / 21);
      const profitGenerated = buyScans.reduce(
        (sum, s) => sum + (parseFloat(s.profit_gbp) || 0),
        0
      );

      setStats({
        co2Saved,
        itemsRescued,
        treesEquivalent,
        profitGenerated: Math.floor(profitGenerated),
      });
    };

    fetchStats();
  }, []);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setAnimate(true);
          observer.disconnect();
        }
      },
      { threshold: 0.3 }
    );
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, []);

  return (
    <section ref={ref} className="bg-black py-14 border-t border-gray-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-10">
          <span className="text-xs font-semibold tracking-widest text-green-400 uppercase">
            Live Community Impact
          </span>
          <h2 className="text-2xl font-bold text-white mt-2">
            Every flip makes a difference
          </h2>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-6 md:gap-0 md:divide-x md:divide-gray-700">
          <StatCard
            icon="ri-leaf-line"
            value={stats.co2Saved}
            label="kg CO₂ saved"
            suffix=" kg"
            animate={animate}
            color="bg-green-900/60 text-green-400"
          />
          <StatCard
            icon="ri-t-shirt-line"
            value={stats.itemsRescued}
            label="items rescued from landfill"
            animate={animate}
            color="bg-emerald-900/60 text-emerald-400"
          />
          <StatCard
            icon="ri-plant-line"
            value={stats.treesEquivalent}
            label="trees equivalent planted"
            animate={animate}
            color="bg-teal-900/60 text-teal-400"
          />
          <StatCard
            icon="ri-money-pound-circle-line"
            value={stats.profitGenerated}
            label="profit generated by users"
            prefix="£"
            animate={animate}
            color="bg-yellow-900/60 text-yellow-400"
          />
        </div>
      </div>
    </section>
  );
}
